### ISSUE TITLE
feature importance

### ISSUE THREAD

**Issue by flopflip** [mlampros/RGF#2]
I believe feature importance was recently implemented in the underlying python code - would it be possible to add access to it?

**Comment by mlampros** [comment]
@flopflip,

based on the [tests of the newly created feature importance](https://github.com/RGF-team/rgf_python/commit/535f5d78be4761c53b66ba65885855afda51d7ba#diff-d9644078adcc2638dbc3821e9f7d2b3b) I guess you already have access to it, but I can't confirm this because I have an older version of rgf-python installed. If you have rgf-python installed after April 2018  then by doing, 

```R

library(RGF)

set.seed(1)
x = matrix(runif(1000), nrow = 100, ncol = 10)
y = sample(1:2, 100, replace = TRUE)

RGF_class = RGF_Classifier$new(max_leaf = 50)

RGF_class$fit(x, y)

RGF_class$.__enclos_env__$private$rgf_init$feature_importances_
```

you can access the new feature. This is just a temporary solution and I'll add a new method for this feature in the next version of the package.

Please test it and let me know. If this doesn't work, I'll install the new version of rgf-python from source tonight.

**Comment by StrikerRUS** [comment]
Hi guys!
We've uploaded the new version (`3.2.0`) of `rgf_python` at PyPI today.

**Comment by mlampros** [comment]
@StrikerRUS,

thanks for the information. I'd like to ask if it's possible to add a ChangeLog file so that users (like me) are able to keep up with changes in the rgf_python package. For instance, the fuzzywuzzy python-package that I ported from python to R has [one](https://github.com/seatgeek/fuzzywuzzy/blob/master/CHANGES.rst). Should I open an issue in the rgf_python repository for this case?

**Comment by StrikerRUS** [comment]
@mlampros Yeah, of course, you can open the issue with this proposal. However, we already have the changelog: we publish it in "Releases" page at GitHub (yes, not the best place): https://github.com/RGF-team/rgf_python/releases.

**Comment by mlampros** [comment]
@StrikerRUS,

thanks for the info, I wasn't aware of the releases field. So, no need to open a issue.
