### ISSUE TITLE
AUC?

### ISSUE THREAD

**Issue by ssobel** [mlampros/RGF#3]
Hi Lampros, would it be possible to add the objective of maximizing AUC as an additional option, along with the current "LS", "Expo", and "Log" loss functions? Thank you.

**Comment by mlampros** [comment]
@ssobel,

as you already know the RGF R package ports the [rgf_python](https://github.com/RGF-team/rgf/tree/master/python-package) library. Therefore, I think you should ask the authors / maintainers of *rgf_python* if your feature request is feasible. If that is the case then I'll be happy to port the new loss (AUC) in the RGF R package in a future version.

**Comment by ssobel** [comment]
@mlampros Hi Lampros, thanks, I will post my question to the team of the rgf_python package. Take care.

**Comment by mlampros** [comment]
@ssobel Hello,

I found out you already asked about the [new loss function](https://github.com/RGF-team/rgf/issues/199). Before I close the issue I'd like to inform you that I updated the RGF package to correspond to the most recent version of *rgf_python* and due to the fact that you had some difficulties installing the package on Windows you should know that I added also a [Singularity image](http://mlampros.github.io/2018/07/26/singularity_containers/) which makes the installation of RGF on a cloud instance pretty straightforward.

**Comment by mlampros** [comment]
@ssobel, I close the issue for now, feel free to reopen it.
